//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionInvestigation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public long MyID { get; set; }
        public Nullable<long> QueueID { get; set; }
        public Nullable<long> HealthBookID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<long> GestationalWeek { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> beforeWeight { get; set; }
        public Nullable<double> currentWeight { get; set; }
    }
}
