//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionInvestigation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDBEntities : DbContext
    {
        public myDBEntities()
            : base("name=myDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<CustomerInputRecord> CustomerInputRecords { get; set; }
        public virtual DbSet<DataTransferRecord> DataTransferRecords { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<FoodClass> FoodClasses { get; set; }
        public virtual DbSet<FoodIntakeRecord> FoodIntakeRecords { get; set; }
        public virtual DbSet<FoodNutrition> FoodNutritions { get; set; }
        public virtual DbSet<FoodStatic> FoodStatics { get; set; }
        public virtual DbSet<FoodStaticResult> FoodStaticResults { get; set; }
        public virtual DbSet<NuritiveElement> NuritiveElements { get; set; }
        public virtual DbSet<NutritionStatisticResult> NutritionStatisticResults { get; set; }
        public virtual DbSet<PrintLog> PrintLogs { get; set; }
        public virtual DbSet<RNIStandard> RNIStandards { get; set; }
    }
}
