//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionInvestigation
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodClass()
        {
            this.FoodNutritions = new HashSet<FoodNutrition>();
        }
    
        public long MyID { get; set; }
        public string FoodClassName { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ParentName { get; set; }
        public Nullable<long> Percent { get; set; }
        public Nullable<long> Edible { get; set; }
        public Nullable<long> RecordMode { get; set; }
        public string TypicalFood { get; set; }
        public string FoodIndex { get; set; }
        public string FoodUnit { get; set; }
        public Nullable<short> needInput { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodNutrition> FoodNutritions { get; set; }
    }
}
