//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionInvestigation
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintLog
    {
        public long MyID { get; set; }
        public Nullable<long> OperatorID { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.DateTime> PrintDateTime { get; set; }
        public Nullable<short> PrintResult { get; set; }
    }
}
