//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionInvestigation
{
    using System;
    using System.Collections.Generic;
    
    public partial class RNIStandard
    {
        public long MyID { get; set; }
        public Nullable<long> Stage { get; set; }
        public Nullable<double> Kcal { get; set; }
        public Nullable<double> Kj { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Fat { get; set; }
        public Nullable<double> Carbo { get; set; }
        public Nullable<double> Fiber { get; set; }
        public Nullable<double> Ca { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> Na { get; set; }
        public Nullable<double> Mg { get; set; }
        public Nullable<double> Fe { get; set; }
        public Nullable<double> Zn { get; set; }
        public Nullable<double> Se { get; set; }
        public Nullable<double> Cu { get; set; }
        public Nullable<double> Mn { get; set; }
        public Nullable<double> Cholestl { get; set; }
        public Nullable<double> Rentinol { get; set; }
        public Nullable<double> Caroten { get; set; }
        public Nullable<double> Vita { get; set; }
        public Nullable<double> Vc { get; set; }
        public Nullable<double> Ve { get; set; }
        public Nullable<double> Thianmin { get; set; }
        public Nullable<double> Riboflav { get; set; }
        public Nullable<double> Niacin { get; set; }
    }
}
